### ISSUE TITLE
Just A Simple Question

### ISSUE THREAD

**Issue by Slok7565** [NikoCat233/TOHE-Niko#1]
I would like to know how do you realize "Can Public"?
It's just remove “Switch Server Interfaces To 2000,0,0,0” or you have a better solution？
That is what i wanna know, ours and all host only mod have this issue
And, Wish your Mod will become better!

我想知道你是如何实现“可以公开”的？
它只是删除“将服务器接口切换到2000,0,0,0”，或者你有更好的解决方案？
这就是我想知道的，我们的模组和所有H系的mod都有这个问题
当然了，希望你的Mod也会变得更好！

**Comment by NikoCat233** [comment]
请看b站私信，这个问题不便公开回答。
